# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 373424b2930e93b00c9860cf8b385019ddc435338fa8bd3a202a7fb22981bcd829ae5363214d617064b772c739fbf56a2d009f97b798fc95c97686a7e27cdcd4

test:
  secret_key_base: 4a6885003049fcfc2f06ce13c1dd0cf14f495567169948af6b625f49c20753b75785cc4aee8fef652348bb78d8460493383fc88cb91569204d1ae9b8bf0368dc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
